### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by mohammad-jamal** [mfechat/AnimeXStream#6]
App not working. Also app from amin repo also not working. Might be some URL issue. Please fix.![Screenshot_2021-06-30-17-41-56-81.jpg](https://user-images.githubusercontent.com/23707225/123959615-011a7900-d9cc-11eb-89da-7f7ef76159d1.jpg)

**Comment by pokurt** [comment]
> App not working. Also app from amin repo also not working. Might be some URL issue. Please fix.![Screenshot_2021-06-30-17-41-56-81.jpg](https://user-images.githubusercontent.com/23707225/123959615-011a7900-d9cc-11eb-89da-7f7ef76159d1.jpg)

![Screenshot_2021-07-02-06-41-36-312_net pokurt aniryu](https://user-images.githubusercontent.com/43902347/124208278-a6366e00-db00-11eb-8ef1-63c751d06c7e.jpg)
works fine on my fork of animeXstream

**Comment by vapormusic** [comment]
yeah, just domain error, fix tomorrow (maybe?)

**Comment by mohammad-jamal** [comment]
fixed?

**Comment by vapormusic** [comment]
@mohammad-jamal fixed (partially) .
